
exports.getPresets = async (req, res) => {

    
      const defaultPresets = [
            {
        
          name: "Default Dashboard",
          primaryColor: "#f97316",
          secondaryColor: "#64748b",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)",
            subSectionBackground: "#ffffff",
            cardColor: "#ffffff",
            cardHeaderColor: "#f97316",
            modalColor: "#ffffff",
            modalCrossBackgroundColor: "#ef4444",
            modalCrossColor: "#ffffff",
            mainTextColor: "#1e293b",
            subTextColor: "#64748b",
            buttonBackground: "#f97316",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#ea580c",
            buttonHoverTextColor: "#fff7ed",
            sidebarBackground: "linear-gradient(180deg, #1e293b 0%, #334155 100%)",
            sidebarLinkColor: "#cbd5e1",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#f97316",
            sidebarActiveBackground: "#f97316",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Ocean Breeze",
          primaryColor: "#0ea5e9",
          secondaryColor: "#64748b",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
            subSectionBackground: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
            cardColor: "#ffffff",
            cardHeaderColor: "#0ea5e9",
            modalColor: "#ffffff",
            modalCrossBackgroundColor: "#0ea5e9",
            modalCrossColor: "#ffffff",
            mainTextColor: "#1e293b",
            subTextColor: "#64748b",
            buttonBackground: "#3b82f6",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#2563eb",
            buttonHoverTextColor: "#dbeafe",
            sidebarBackground: "linear-gradient(180deg, #1e293b 0%, #334155 100%)",
            sidebarLinkColor: "#cbd5e1",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#3b82f6",
            sidebarActiveBackground: "#2563eb",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Sunset Glow",
          primaryColor: "#f97316",
          secondaryColor: "#a3a3a3",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #fad0c4 0%, #ffd1ff 100%)",
            subSectionBackground: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
            cardColor: "#fffaf0",
            cardHeaderColor: "#f97316",
            modalColor: "#fffaf0",
            modalCrossBackgroundColor: "#ea580c",
            modalCrossColor: "#ffffff",
            mainTextColor: "#92400e",
            subTextColor: "#a78bfa",
            buttonBackground: "#ea580c",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#c2410c",
            buttonHoverTextColor: "#fef3c7",
            sidebarBackground: "linear-gradient(180deg, #451a03 0%, #7c2d12 100%)",
            sidebarLinkColor: "#fed7aa",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#ea580c",
            sidebarActiveBackground: "#c2410c",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Forest Green",
          primaryColor: "#059669",
          secondaryColor: "#6b7280",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #e0f2f1 0%, #b2dfdb 100%)",
            subSectionBackground: "linear-gradient(135deg, #a7ffeb 0%, #1de9b6 100%)",
            cardColor: "#f0fdf4",
            cardHeaderColor: "#059669",
            modalColor: "#f0fdf4",
            modalCrossBackgroundColor: "#047857",
            modalCrossColor: "#ffffff",
            mainTextColor: "#064e3b",
            subTextColor: "#374151",
            buttonBackground: "#047857",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#065f46",
            buttonHoverTextColor: "#d1fae5",
            sidebarBackground: "linear-gradient(180deg, #064e3b 0%, #065f46 100%)",
            sidebarLinkColor: "#a7f3d0",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#047857",
            sidebarActiveBackground: "#059669",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Royal Purple",
          primaryColor: "#7c3aed",
          secondaryColor: "#a78bfa",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #6a11cb 0%, #2575fc 100%)",
            subSectionBackground: "linear-gradient(135deg, #c471f5 0%, #fa71cd 100%)",
            cardColor: "#faf5ff",
            cardHeaderColor: "#7c3aed",
            modalColor: "#faf5ff",
            modalCrossBackgroundColor: "#a855f7",
            modalCrossColor: "#ffffff",
            mainTextColor: "#581c87",
            subTextColor: "#6b21a8",
            buttonBackground: "#7c3aed",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#6d28d9",
            buttonHoverTextColor: "#f3e8ff",
            sidebarBackground: "linear-gradient(180deg, #1e1b4b 0%, #312e81 100%)",
            sidebarLinkColor: "#c4b5fd",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#7c3aed",
            sidebarActiveBackground: "#a855f7",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Dark Mode",
          primaryColor: "#2563eb",
          secondaryColor: "#9ca3af",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
            subSectionBackground: "linear-gradient(135deg, #374151 0%, #4b5563 100%)",
            cardColor: "#1f2937",
            cardHeaderColor: "#2563eb",
            modalColor: "#1f2937",
            modalCrossBackgroundColor: "#ef4444",
            modalCrossColor: "#ffffff",
            mainTextColor: "#f9fafb",
            subTextColor: "#d1d5db",
            buttonBackground: "#2563eb",
            buttonTextColor: "#f9fafb",
            buttonHoverBackground: "#1e40af",
            buttonHoverTextColor: "#dbeafe",
            sidebarBackground: "linear-gradient(180deg, #111827 0%, #1f2937 100%)",
            sidebarLinkColor: "#9ca3af",
            sidebarLinkHoverColor: "#f3f4f6",
            sidebarLinkHoverBackground: "#374151",
            sidebarActiveBackground: "#2563eb",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Emerald Sea",
          primaryColor: "#10b981",
          secondaryColor: "#6ee7b7",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%)",
            subSectionBackground: "linear-gradient(135deg, #6ee7b7 0%, #34d399 100%)",
            cardColor: "#f0fdf4",
            cardHeaderColor: "#10b981",
            modalColor: "#f0fdf4",
            modalCrossBackgroundColor: "#059669",
            modalCrossColor: "#ffffff",
            mainTextColor: "#064e3b",
            subTextColor: "#047857",
            buttonBackground: "#10b981",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#059669",
            buttonHoverTextColor: "#d1fae5",
            sidebarBackground: "linear-gradient(180deg, #022c22 0%, #064e3b 100%)",
            sidebarLinkColor: "#a7f3d0",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#10b981",
            sidebarActiveBackground: "#059669",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Rose Gold",
          primaryColor: "#f43f5e",
          secondaryColor: "#fda4af",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)",
            subSectionBackground: "linear-gradient(135deg, #fbcfe8 0%, #f9a8d4 100%)",
            cardColor: "#fef7f7",
            cardHeaderColor: "#f43f5e",
            modalColor: "#fef7f7",
            modalCrossBackgroundColor: "#e11d48",
            modalCrossColor: "#ffffff",
            mainTextColor: "#881337",
            subTextColor: "#be185d",
            buttonBackground: "#f43f5e",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#e11d48",
            buttonHoverTextColor: "#fce7f3",
            sidebarBackground: "linear-gradient(180deg, #4c0519 0%, #881337 100%)",
            sidebarLinkColor: "#fce7f3",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#f43f5e",
            sidebarActiveBackground: "#e11d48",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Sky Blue",
          primaryColor: "#0ea5e9",
          secondaryColor: "#7dd3fc",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)",
            subSectionBackground: "linear-gradient(135deg, #bae6fd 0%, #7dd3fc 100%)",
            cardColor: "#f8fafc",
            cardHeaderColor: "#0ea5e9",
            modalColor: "#f8fafc",
            modalCrossBackgroundColor: "#0284c7",
            modalCrossColor: "#ffffff",
            mainTextColor: "#0c4a6e",
            subTextColor: "#0369a1",
            buttonBackground: "#0ea5e9",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#0284c7",
            buttonHoverTextColor: "#e0f2fe",
            sidebarBackground: "linear-gradient(180deg, #0c4a6e 0%, #075985 100%)",
            sidebarLinkColor: "#bae6fd",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#0ea5e9",
            sidebarActiveBackground: "#0284c7",
            sidebarActiveLinkColor: "#ffffff",
          }
        },
        {
          name: "Amber Sunset",
          primaryColor: "#f59e0b",
          secondaryColor: "#fbbf24",
          theme: {
            mainSectionBackground: "linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)",
            subSectionBackground: "linear-gradient(135deg, #fde68a 0%, #f59e0b 100%)",
            cardColor: "#fffbeb",
            cardHeaderColor: "#f59e0b",
            modalColor: "#fffbeb",
            modalCrossBackgroundColor: "#d97706",
            modalCrossColor: "#ffffff",
            mainTextColor: "#78350f",
            subTextColor: "#92400e",
            buttonBackground: "#f59e0b",
            buttonTextColor: "#ffffff",
            buttonHoverBackground: "#d97706",
            buttonHoverTextColor: "#fef3c7",
            sidebarBackground: "linear-gradient(180deg, #451a03 0%, #78350f 100%)",
            sidebarLinkColor: "#fde68a",
            sidebarLinkHoverColor: "#ffffff",
            sidebarLinkHoverBackground: "#f59e0b",
            sidebarActiveBackground: "#d97706",
            sidebarActiveLinkColor: "#ffffff",
          }
        }
      ];
   
    
    res.json(defaultPresets);
  } 

